name: Release

on:
  workflow_call:
    inputs:
      packer-path:
        description: 'Path to Packer file in the repo'
        required: true
        type: string

      runs-on:
        description: 'Where to run, usually ubuntu-latest or self-hosted'
        default: 'self-hosted'
        required: false
        type: string

      aws-region:
        description: 'AWS region'
        default: 'eu-west-2'
        required: false
        type: string

    secrets:
      aws-account:
        description: 'AWS account ID'
        required: true
      gh-pat:
        description: 'Github PAT of CI user'
        required: true
      ami-users:
        description: 'A list of AWS account IDs to share the AMI with, e.g. ["12345678","87654321"]'
        required: false

jobs:
  plan:
    name: Packer Release
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: push_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh-pat }}
          RELEASE_BRANCHES: 'main'
          WITH_V: true

      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ${{ inputs.packer-path }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account }}:role/ci
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ inputs.aws-region }}

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ${{ inputs.packer-path }}
        env:
          PACKER_LOG: 1

      - name: Packer Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: ${{ inputs.packer-path }}
        env:
          PACKER_LOG: 1
          PKR_VAR_is_pull_request: false
          PKR_VAR_commit_sha: ${{ github.event.head_commit.id }}
          PKR_VAR_repo: ${{ github.repository }}
          PKR_VAR_ami_users: ${{ secrets.ami-users }}
          PKR_VAR_release_tag: ${{ steps.push_tag.outputs.new_tag }}
