name: Apply

on:
  workflow_call:
    inputs:
      tfvars:
        description: 'tfvar file and backend-config identifier'
        required: true
        type: string

      tf_version:
        description: 'Terraform version to run'
        default: '1.1.8'
        required: false
        type: string

      runs-on:
        description: 'Where to run, usually ubuntu-latest or self-hosted'
        default: 'self-hosted'
        required: false
        type: string

      aws-region:
        description: 'AWS region'
        default: 'eu-west-2'
        required: false
        type: string

    secrets:
      aws-account:
        description: 'AWS account ID'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account }}:role/ci
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform apply
        working-directory: ./terraform
        id: tf-apply
        env:
          TF_WORKSPACE: default
        run: |
          terraform init -backend-config=tfvars/${{ inputs.tfvars }}.backend.tfvars
          terraform apply -auto-approve -var-file=tfvars/${{ inputs.tfvars }}.tfvars

      - name: Terraform plan
        working-directory: ./terraform
        id: tf-plan
        env:
          TF_WORKSPACE: default
        run: |
          terraform init -backend-config=tfvars/${{ inputs.tfvars }}.backend.tfvars
          terraform plan -detailed-exitcode -var-file=tfvars/${{ inputs.tfvars }}.tfvars
