name: Pull request

on:
  workflow_call:
    inputs:
      tfvars:
        description: 'tfvar file and backend-config identifier'
        required: true
        type: string

      tf_version:
        description: 'Terraform version to run'
        default: '1.1.8'
        required: false
        type: string

      checkov_check:
        description: 'Comma-separated list of Checkov tests to perform'
        default: ''
        required: false
        type: string

      checkov_skip_check:
        description: 'Comma-separated list of Checkov tests to skip'
        default: ''
        required: false
        type: string

      runs-on:
        description: 'Where to run, usually ubuntu-latest or self-hosted'
        default: 'self-hosted'
        required: false
        type: string

      aws-region:
        description: 'AWS region'
        default: 'eu-west-2'
        required: false
        type: string

    secrets:
      aws-account:
        description: 'AWS account ID'
        required: true
      gh-pat:
        description: 'Github PAT of CI user'
        required: true

jobs:
  plan:
    name: Terraform plan
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform Format
        working-directory: ./terraform
        id: fmt
        run: terraform fmt -recursive -check -diff
        continue-on-error: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account }}:role/ci
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform plan
        working-directory: ./terraform
        id: tf-plan
        env:
          TF_WORKSPACE: default
        run: |
          git config --global url."https://oauth2:${{ secrets.gh-pat }}@github.com".insteadOf https://github.com
          terraform --version
          terraform init -backend-config=tfvars/${{ inputs.tfvars }}.backend.tfvars
          terraform plan -var-file=tfvars/${{ inputs.tfvars }}.tfvars

  checkov:
    name: Run Checkov
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          check: ${{ inputs.checkov_check }}
          skip_check: ${{ inputs.checkov_skip_check }}
          soft_fail: false # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          log_level: WARNING # optional: set log level. Default WARNING
