name: Terraform Release

on:
  workflow_call:
    inputs:
      tfvars:
        description: 'tfvar file and backend-config identifier'
        required: true
        type: string

      working-directory:
        description: 'Working directory containing terraform code to run'
        default: 'terraform'
        required: false
        type: string

      tf_version:
        description: 'Terraform version to run'
        default: '1.1.8'
        required: false
        type: string

      runs-on:
        description: 'Where to run, usually ubuntu-latest or self-hosted'
        default: 'self-hosted'
        required: false
        type: string

      aws-region:
        description: 'AWS region'
        default: 'eu-west-2'
        required: false
        type: string

    secrets:
      aws-account:
        description: 'AWS account ID'
        required: true
      gh-pat:
        description: 'Github PAT of CI user'
        required: true

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh-pat }}
          RELEASE_BRANCHES: 'main'
          WITH_V: true

  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs-on }}
#    defaults:
#      run:
#        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform version
        working-directory: ./${{ inputs.working-directory }}
        id: version
        run: terraform --version
        continue-on-error: false

      - name: Terraform fmt
        working-directory: ./${{ inputs.working-directory }}
        id: fmt
        run: terraform fmt -recursive -check -diff
        continue-on-error: false

      - name: Configure Github credentials
        run: git config --global url."https://oauth2:${{ secrets.gh-pat }}@github.com".insteadOf https://github.com

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account }}:role/ci
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform init
        working-directory: ./${{ inputs.working-directory }}
        id: init
        run: terraform init -backend-config=tfvars/${{ inputs.tfvars }}.backend.tfvars
        continue-on-error: false

      - name: Terraform apply
        working-directory: ./${{ inputs.working-directory }}
        id: apply
        env:
          TF_WORKSPACE: default
        run: terraform apply -input=false -auto-approve -var-file=tfvars/${{ inputs.tfvars }}.tfvars
        continue-on-error: false

      - name: Terraform plan
        working-directory: ./${{ inputs.working-directory }}
        id: plan
        env:
          TF_WORKSPACE: default
        run: terraform plan -input=false -detailed-exitcode -var-file=tfvars/${{ inputs.tfvars }}.tfvars